version: '3'
services:

  mongodb:
      image: mongo:latest
      container_name: mongodb
      hostname: mongodb
      restart: always
      networks:
        - postgres-network
      ports:
        - 27017:27017
        
  mongoclient:
      image: mongoclient/mongoclient:latest
      container_name: mongoclient
      hostname: mongoclient
      restart: always
      depends_on:
        - mongodb
      networks:
        - postgres-network
      ports:
        - 3300:3000 

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "1568:5432"
    restart: always
    volumes:
      - './pgadmin:/var/lib/postgresql/data' 
    networks:
      - postgres-network

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "andre@yahoo.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    container_name: pgadmin
    ports:
      - "4000:80"
    restart: always  
    depends_on:
      - postgres
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge      
      




